name: Keep Render App Alive

on:
  schedule:
    - cron: '*/5 * * * *'  # Chạy mỗi 5 phút

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render App
        run: curl -I https://social-network-lle3.onrender.com/
